name: Deploy static content to Pages
on:
  push:
    branches: [master]
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

# ---------- apply this default -------------
defaults:
  run:
    working-directory: chantMIR/mir-choral   # <── your project folder

# -------------------------------------------

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22          # or 22


      - name: Install dependencies
        run: npm install            # or npm ci if you add package-lock.json

      - name: Build
        run: npm run build          # outputs to ./dist inside working-dir

      - uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'            # relative to working-dir

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
